# Copyright (c) Linumiz 2024

manifest:

  remotes:
    - name: rixx
      url-base: https://github.com/linumiz

    - name: zephyr
      url-base: https://github.com/zephyrproject-rtos

    - name: flashDB
      url-base: https://github.com/armink

  projects:
# zephyr
    - name: zephyr
      remote: zephyr
      revision: main
      path: zephyr
      import: true

# rixx sdk modules
    # FlashDB
    - name: FlashDB
      remote: flashDB
      revision: 523fd2052d13baf72fd1d8e177c2a162a03392be
      path: modules/lib/flashdb

   #json-c
    - name: json-c
      remote: rixx
      revision: dev/zephyr
      path: modules/lib/json-c
